name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_ACR_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.AZURE_ACR_SERVER }}/c-program-test:latest .

      # Step 5: Push the Docker image to ACR
      - name: Push Docker Image to ACR
        run: docker push ${{ secrets.AZURE_ACR_SERVER }}/c-program-test:latest
